---
- hosts: all
  tasks:
    - name: find files biger than 10Mb 
      find:
        paths: /var/log
        patterns: [ '*.log', '*.old' ]
      register: find_result
    
    - name: Print version
      debug:
        msg: "Busqueda completa {{ find_result.path }}"
