---
- hosts: all
  tasks:
    - name: find files biger than 10Mb 
      find:
        paths: /var/log
        size: 10m
        register: files_matched
    
    - debug:
      msg: "{{ files_matched.files }}"
